In [2]:
import warnings

warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import os

import talib

import gymnasium as gym


import collections
import argparse

import math
import random
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple, deque
from itertools import count

import seaborn as sns
import pandas as pd

In [2]:
from DataManager import ZipDataMerger


merger = ZipDataMerger()

In [3]:
merger.run()

In [5]:
import os

sub_dir = 'temp_directory'
os.mkdir(sub_dir)

In [ ]:
with open(".gitignore", "w") as gitignore_file:
    gitignore_file.write()

In [2]:
import gzip

In [3]:
base_data = pd.read_csv('Full_Data.csv')

In [7]:
import os

In [4]:
base_data.to_csv('./temp_directory/temp.csv')

In [ ]:
os.path.join()

In [ ]:
base_data.to_csv

In [8]:
int(len(base_data) / 3)

4954525

In [9]:
base_data

,Time Stamp,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
0,715589,137649533,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,ANONYMOUS LOGON@C457 C457 C457,0
1,715589,137649534,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,ANONYMOUS LOGON@C467 C467 C467,0
2,715589,137649535,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,ANONYMOUS LOGON@C586 C586 C586,0
3,715589,137649536,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C5995 C586,0
4,715589,137649537,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C6931 C586,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14863570,777813,152513103,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,U8857@DOM1 C528 C528,0
14863571,777813,152513104,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,U953@DOM1 C803 C1065,0
14863572,777813,152513105,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,U9861@DOM1 C457 C457,0
14863573,777813,152513106,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,U996@DOM1 C10 C10,0
14863574,777813,152513107,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,U996@DOM1 C3173 C3173,0

In [23]:
base_data.columns

Index(['Time Stamp', 'Unnamed: 0', 'Source_Dome', 'Dest_Dome', 'Source_PC',
       'Destination_PC', 'auth_type', 'logon_type', 'Auth Orientation',
       'result', 'test', 'target'],
      dtype='object')

In [28]:
# base_data[[
#     'Source_Dome','Source_PC','Destination_PC','test','target'
# ]]

In [46]:
base_data[base_data['target']==1]

,Time Stamp,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
2707024,725488,140356557,U1653@DOM1,U1653@DOM1,C17693,C395,NTLM,Network,LogOn,Success,U1653@DOM1 C17693 C395,1
2734717,725589,140384250,U1653@DOM1,U1653@DOM1,C17693,C2669,NTLM,Network,LogOn,Success,U1653@DOM1 C17693 C2669,1
2845909,725983,140495442,U293@DOM1,U293@DOM1,C17693,C3153,NTLM,Network,LogOn,Success,U293@DOM1 C17693 C3153,1
2853895,726008,140503428,U8946@DOM1,U8946@DOM1,C17693,C1610,NTLM,Network,LogOn,Success,U8946@DOM1 C17693 C1610,1
2867000,726057,140516533,U293@DOM1,U293@DOM1,C17693,C3153,NTLM,Network,LogOn,Success,U293@DOM1 C17693 C3153,1
...,...,...,...,...,...,...,...,...,...,...,...,...
13002351,767320,150651884,U7394@DOM1,U7394@DOM1,C17693,C1797,NTLM,Network,LogOn,Success,U7394@DOM1 C17693 C1797,1
13026365,767445,150675898,U4353@DOM1,U4353@DOM1,C17693,C801,NTLM,Network,LogOn,Success,U4353@DOM1 C17693 C801,1
13093789,767813,150743322,U66@DOM1,U66@DOM1,C17693,C2944,NTLM,Network,LogOn,Success,U66@DOM1 C17693 C2944,1
13499647,770138,151149180,U737@DOM1,U737@DOM1,C17693,C7597,NTLM,Network,LogOn,Success,U737@DOM1 C17693 C7597,1
13721571,771340,151371104,U9763@DOM1,U9763@DOM1,C17693,C353,NTLM,Network,LogOn,Success,U9763@DOM1 C17693 C353,1

In [47]:
base_data[base_data['Time Stamp']==725488]

,Time Stamp,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
2706872,725488,140356405,ANONYMOUS LOGON@C1065,ANONYMOUS LOGON@C1065,C3165,C1065,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C1065 C3165 C1065,0
2706873,725488,140356406,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C5156,C457,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C457 C5156 C457,0
2706874,725488,140356407,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,ANONYMOUS LOGON@C467 C467 C467,0
2706875,725488,140356408,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C10786,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C10786 C586,0
2706876,725488,140356409,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C11636,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C11636 C586,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2707099,725488,140356632,U8999@DOM1,U8999@DOM1,C19092,C457,Kerberos,Network,LogOn,Success,U8999@DOM1 C19092 C457,0
2707100,725488,140356633,U8999@DOM1,U8999@DOM1,C457,C457,?,Network,LogOff,Success,U8999@DOM1 C457 C457,0
2707101,725488,140356634,U9506@DOM1,U9506@DOM1,C20375,C625,?,?,TGS,Success,U9506@DOM1 C20375 C625,0
2707102,725488,140356635,U9573@DOM1,U9573@DOM1,C467,C467,?,Network,LogOff,Success,U9573@DOM1 C467 C467,0
2707103,725488,140356636,U9852@DOM1,U9852@DOM1,C20758,C612,Kerberos,Network,LogOn,Success,U9852@DOM1 C20758 C612,0

In [45]:
base_data[base_data['target']==1][[
    'Source_Dome','Source_PC','Destination_PC','test','target' 
]][50:60]

        Source_Dome Source_PC Destination_PC                      test  target
6495649   U293@DOM1    C17693          C3422    U293@DOM1 C17693 C3422       1
6527900   U293@DOM1    C17693          C3153    U293@DOM1 C17693 C3153       1
6576871   U293@DOM1    C17693            C42      U293@DOM1 C17693 C42       1
6661798  U1600@DOM1    C17693            C92     U1600@DOM1 C17693 C92       1
6669441  U1600@DOM1    C17693         C16088  U1600@DOM1 C17693 C16088       1
6772368  U1600@DOM1    C17693            C92     U1600@DOM1 C17693 C92       1
6995800   U349@DOM1    C17693           C886     U349@DOM1 C17693 C886       1
6997659   U349@DOM1    C17693           C886     U349@DOM1 C17693 C886       1
7022281  U8601@DOM1    C17693         C10817  U8601@DOM1 C17693 C10817       1
7073614  U4353@DOM1    C17693         C15232  U4353@DOM1 C17693 C15232       1

In [29]:
chunk_size = int(len(base_data) / 3)

In [31]:
len(base_data)

14863575

In [36]:
chunk_1_dataframe = base_data.iloc[:chunk_size]
chunk_2_dataframe = base_data.iloc[chunk_size:chunk_size + chunk_size]
chunk_3_dataframe = base_data.iloc[chunk_size + chunk_size : chunk_size * 3]

In [37]:
list1 = [chunk_1_dataframe, chunk_2_dataframe, chunk_3_dataframe]

In [38]:
for n,i in enumerate(list1, 1):
    print(n)

1
2
3

In [39]:
for n,i in enumerate(list1, 1):
    i.to_csv(f"chunk_{n}.csv")

In [40]:
import zipfile

In [49]:
files_list = ['chunk_1.csv', 'chunk_2.csv', 'chunk_3.csv']
compressed_files_list = ['compressed_chunk_1.zip', 'compressed_chunk_2.zip', 'compressed_chunk_3.zip']

In [50]:
list_pairs = [
    (files_list[0], compressed_files_list[0]),
    (files_list[1], compressed_files_list[1]),
    (files_list[2], compressed_files_list[2])
]

In [44]:
list_pairs

[('chunk_1.csv', 'compressed_chunk_1.csv'),
 ('chunk_2.csv', 'compressed_chunk_2.csv'),
 ('chunk_3.csv', 'compressed_chunk_3.csv')]

In [52]:
with zipfile.ZipFile('compressed_chunk_1.zip', 'w', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(files_list[0])

In [53]:
with zipfile.ZipFile(compressed_files_list[1], 'w', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(files_list[1])

In [54]:
with zipfile.ZipFile(compressed_files_list[2], 'w', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(files_list[2])

In [57]:
class ZipDataMerger:
    def __init__(self):
        self.compressed_files_list = [
            'compressed_chunk_1.zip', 'compressed_chunk_2.zip', 'compressed_chunk_3.zip'
        ]
        self.base_files_list = [
            'chunk_1.csv', 'chunk_2.csv', 'chunk_3.csv'
        ]

    
    def read_data(self):
        self.df_list = []

        for compressed_file, base_file in zip(self.compressed_files_list, self.base_files_list):
            with zipfile.ZipFile(compressed_file, 'r') as zipf:
                with zipf.open(base_file) as csv_file:
                    df = pd.read_csv(csv_file)
                    self.df_list.append(df)

In [ ]:
import os

sub_dir = 'temp_directory'
os.mkdir(sub_dir)

In [58]:
tt = ZipDataMerger()
tt.read_data()

In [69]:
df = pd.concat(i for i in tt.df_list)

In [73]:
merger.run()

AttributeError: 'ZipDataMerger' object has no attribute 'run'

In [66]:
df

,Unnamed: 0.1,Time Stamp,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
0,0,715589,137649533,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,ANONYMOUS LOGON@C457 C457 C457,0
1,1,715589,137649534,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,ANONYMOUS LOGON@C467 C467 C467,0
2,2,715589,137649535,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,ANONYMOUS LOGON@C586 C586 C586,0
3,3,715589,137649536,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C5995 C586,0
4,4,715589,137649537,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C6931 C586,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4954520,14863570,777813,152513103,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,U8857@DOM1 C528 C528,0
4954521,14863571,777813,152513104,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,U953@DOM1 C803 C1065,0
4954522,14863572,777813,152513105,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,U9861@DOM1 C457 C457,0
4954523,14863573,777813,152513106,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,U996@DOM1 C10 C10,0
4954524,14863574,777813,152513107,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,U996@DOM1 C3173 C3173,0

In [70]:
df = df.rename({'Unnamed: 0.1':'Integer_index'},axis=1)
df = df.set_index('Integer_index')
df = df.drop(['Unnamed: 0'],axis=1)
df

,Time Stamp,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
Integer_index,,,,,,,,,,,
0,715589,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,ANONYMOUS LOGON@C457 C457 C457,0
1,715589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,ANONYMOUS LOGON@C467 C467 C467,0
2,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,ANONYMOUS LOGON@C586 C586 C586,0
3,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C5995 C586,0
4,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C6931 C586,0
...,...,...,...,...,...,...,...,...,...,...,...
14863570,777813,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,U8857@DOM1 C528 C528,0
14863571,777813,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,U953@DOM1 C803 C1065,0
14863572,777813,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,U9861@DOM1 C457 C457,0
14863573,777813,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,U996@DOM1 C10 C10,0
14863574,777813,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,U996@DOM1 C3173 C3173,0

In [68]:
df.columns

Index(['Time Stamp', 'Unnamed: 0', 'Source_Dome', 'Dest_Dome', 'Source_PC',
       'Destination_PC', 'auth_type', 'logon_type', 'Auth Orientation',
       'result', 'test', 'target'],
      dtype='object')

In [62]:
base_data

,Time Stamp,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
0,715589,137649533,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,ANONYMOUS LOGON@C457 C457 C457,0
1,715589,137649534,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,ANONYMOUS LOGON@C467 C467 C467,0
2,715589,137649535,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,ANONYMOUS LOGON@C586 C586 C586,0
3,715589,137649536,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C5995 C586,0
4,715589,137649537,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C6931 C586,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14863570,777813,152513103,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,U8857@DOM1 C528 C528,0
14863571,777813,152513104,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,U953@DOM1 C803 C1065,0
14863572,777813,152513105,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,U9861@DOM1 C457 C457,0
14863573,777813,152513106,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,U996@DOM1 C10 C10,0
14863574,777813,152513107,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,U996@DOM1 C3173 C3173,0

In [34]:
base_data.iloc[chunk_size:chunk_size + chunk_size]

,Time Stamp,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
4954525,733427,142604058,U7637@DOM1,U7637@DOM1,C3173,C3173,?,Network,LogOff,Success,U7637@DOM1 C3173 C3173,0
4954526,733427,142604059,U7@DOM1,U7@DOM1,C92,U7,?,?,TGS,Success,U7@DOM1 C92 U7,0
4954527,733427,142604060,U8076@DOM1,U8076@DOM1,C3359,C3359,?,?,TGS,Success,U8076@DOM1 C3359 C3359,0
4954528,733427,142604061,U8076@DOM1,U8076@DOM1,C3359,C3359,?,?,TGT,Success,U8076@DOM1 C3359 C3359,0
4954529,733427,142604062,U8083@DOM1,U8083@DOM1,C1795,C1794,?,?,TGS,Success,U8083@DOM1 C1795 C1794,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9909045,751389,147558578,C698$@DOM1,SYSTEM@C698,C698,C698,Negotiate,NewCredentials,LogOn,Success,C698$@DOM1 C698 C698,0
9909046,751389,147558579,C7394$@DOM1,C7394$@DOM1,C7394,C10,Kerberos,Network,LogOn,Success,C7394$@DOM1 C7394 C10,0
9909047,751389,147558580,C74$@DOM1,C74$@DOM1,C74,C457,Kerberos,Network,LogOn,Success,C74$@DOM1 C74 C457,0
9909048,751389,147558581,C7416$@DOM1,C7416$@DOM1,C7416,C457,Kerberos,Network,LogOn,Success,C7416$@DOM1 C7416 C457,0
9909049,751389,147558582,C7416$@DOM1,C7416$@DOM1,C7416,TGT,?,?,TGS,Success,C7416$@DOM1 C7416 TGT,0

In [35]:
base_data.iloc[chunk_size + chunk_size : chunk_size * 3]

,Time Stamp,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,test,target
9909050,751389,147558583,C755$@DOM1,C755$@DOM1,C625,C625,?,Network,LogOff,Success,C755$@DOM1 C625 C625,0
9909051,751389,147558584,C755$@DOM1,C755$@DOM1,C755,C625,Kerberos,Network,LogOn,Success,C755$@DOM1 C755 C625,0
9909052,751389,147558585,C8458$@DOM1,C8458$@DOM1,C8458,C529,Kerberos,Network,LogOn,Success,C8458$@DOM1 C8458 C529,0
9909053,751389,147558586,C8585$@DOM1,C8585$@DOM1,C625,C625,?,Network,LogOff,Success,C8585$@DOM1 C625 C625,0
9909054,751389,147558587,C8802$@DOM1,C8802$@DOM1,C3173,C3173,?,Network,LogOff,Success,C8802$@DOM1 C3173 C3173,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14863570,777813,152513103,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,U8857@DOM1 C528 C528,0
14863571,777813,152513104,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,U953@DOM1 C803 C1065,0
14863572,777813,152513105,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,U9861@DOM1 C457 C457,0
14863573,777813,152513106,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,U996@DOM1 C10 C10,0
14863574,777813,152513107,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,U996@DOM1 C3173 C3173,0

In [ ]:
base_data[]

In [6]:
len(base_data)

14863575

In [3]:
with open('Full_Data.csv', 'rb') as f_in:
    with gzip.open('compressed_full.csv.gz', 'wb') as f_out:
        f_out.writelines(f_in)

In [2]:
from Step import TimeStep

In [3]:
env = TimeStep()

In [23]:
env.current_step = 0

In [220]:
env.current_step = 9885

In [336]:

obs = env.step()

obs = obs.sort_values(by='target', ascending=False)
obs

,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,target
Time Stamp,,,,,,,,,
725589,U1653@DOM1,U1653@DOM1,C17693,C2669,NTLM,Network,LogOn,Success,1
725589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,0
725589,U3399@DOM1,U3399@DOM1,C9064,C457,Kerberos,Network,LogOn,Success,0
725589,U2390@DOM1,U2390@DOM1,C529,C529,?,Network,LogOff,Success,0
725589,U2437@DOM1,U2437@DOM1,C19978,C449,Kerberos,Network,LogOn,Success,0
...,...,...,...,...,...,...,...,...,...
725589,C3015$@DOM1,C3015$@DOM1,C528,C528,?,Network,LogOff,Success,0
725589,C3015$@DOM1,C3015$@DOM1,C529,C529,?,Network,LogOff,Success,0
725589,C3015$@DOM1,C3015$@DOM1,C612,C612,?,Network,LogOff,Success,0
725589,C3015$@DOM1,C3015$@DOM1,C625,C625,?,Network,LogOff,Success,0
725589,U97@DOM1,U97@DOM1,C2162,C2162,?,Network,LogOff,Success,0

In [74]:
env.current_step

30

In [47]:
targets = env.base_data[env.base_data['target']==1]
targets

,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,target
Time Stamp,,,,,,,,,
725488,U1653@DOM1,U1653@DOM1,C17693,C395,NTLM,Network,LogOn,Success,1
725589,U1653@DOM1,U1653@DOM1,C17693,C2669,NTLM,Network,LogOn,Success,1
725983,U293@DOM1,U293@DOM1,C17693,C3153,NTLM,Network,LogOn,Success,1
726008,U8946@DOM1,U8946@DOM1,C17693,C1610,NTLM,Network,LogOn,Success,1
726057,U293@DOM1,U293@DOM1,C17693,C3153,NTLM,Network,LogOn,Success,1
...,...,...,...,...,...,...,...,...,...
767320,U7394@DOM1,U7394@DOM1,C17693,C1797,NTLM,Network,LogOn,Success,1
767445,U4353@DOM1,U4353@DOM1,C17693,C801,NTLM,Network,LogOn,Success,1
767813,U66@DOM1,U66@DOM1,C17693,C2944,NTLM,Network,LogOn,Success,1
770138,U737@DOM1,U737@DOM1,C17693,C7597,NTLM,Network,LogOn,Success,1
771340,U9763@DOM1,U9763@DOM1,C17693,C353,NTLM,Network,LogOn,Success,1

In [50]:
env.base_data['Destination_PC'].value_counts()

C586      1832959
C612      1194362
C529      1160703
C457      1100756
C625      1057538
           ...
C21760          1
C21330          1
C10193          1
C10536          1
C5832           1
Name: Destination_PC, Length: 11606, dtype: int64

In [48]:
targets['auth_type'].value_counts()

NTLM    205
Name: auth_type, dtype: int64

In [49]:
targets['Destination_PC'].value_counts()

C3153    6
C1448    6
C395     5
C9945    5
C1784    5
        ..
C1477    1
C90      1
C2578    1
C3601    1
C2944    1
Name: Destination_PC, Length: 127, dtype: int64

In [43]:
env.current_step -= 1

In [44]:
obs = env.array_step()
obs.shape

(212, 9)

In [160]:
env.data

array([['ANONYMOUS LOGON@C457', 'ANONYMOUS LOGON@C457', 'C457', ...,
        'LogOff', 'Success', 0],
       ['ANONYMOUS LOGON@C467', 'ANONYMOUS LOGON@C467', 'C467', ...,
        'LogOff', 'Success', 0],
       ['ANONYMOUS LOGON@C586', 'ANONYMOUS LOGON@C586', 'C586', ...,
        'LogOff', 'Success', 0],
       ...,
       ['U9861@DOM1', 'U9861@DOM1', 'C457', ..., 'LogOff', 'Success', 0],
       ['U996@DOM1', 'U996@DOM1', 'C10', ..., 'LogOff', 'Success', 0],
       ['U996@DOM1', 'U996@DOM1', 'C3173', ..., 'LogOff', 'Success', 0]],
      dtype=object)

In [384]:
env.step()

,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,target
Time Stamp,,,,,,,,,
715968,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,0
715968,ANONYMOUS LOGON@C5836,ANONYMOUS LOGON@C5836,C5836,C5836,?,Network,LogOff,Success,0
715968,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,0
715968,C1025$@DOM1,C1025$@DOM1,C561,C561,?,Network,LogOff,Success,0
715968,C104$@DOM1,C104$@DOM1,C523,C523,?,Network,LogOff,Success,0
...,...,...,...,...,...,...,...,...,...
715968,U9714@DOM1,U9714@DOM1,C1060,C1065,Kerberos,Network,LogOn,Success,0
715968,U9714@DOM1,U9714@DOM1,C1065,C1065,?,Network,LogOff,Success,0
715968,U9714@DOM1,U9714@DOM1,C529,C529,?,Network,LogOff,Success,0
715968,U9836@DOM1,U9836@DOM1,C20736,C2327,?,?,TGS,Success,0
715968,U996@DOM1,U996@DOM1,C11309,C3173,Kerberos,Network,LogOn,Success,0

In [392]:
env.base_data.loc[env.index_array[env.current_step]].__len__()

188

In [395]:
env.base_data.loc[env.index_array[env.current_step]]

,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,target
Time Stamp,,,,,,,,,
715589,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,0
715589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,0
...,...,...,...,...,...,...,...,...,...
715589,U968@DOM1,U968@DOM1,C1065,C1065,?,Network,LogOff,Success,0
715589,U968@DOM1,U968@DOM1,C467,C467,?,Network,LogOff,Success,0
715589,U968@DOM1,U968@DOM1,C822,C1065,Kerberos,Network,LogOn,Success,0
715589,U968@DOM1,U968@DOM1,C822,C467,Kerberos,Network,LogOn,Success,0
715589,U9927@DOM1,U9927@DOM1,C20919,C586,Kerberos,Network,LogOn,Success,0

In [394]:
env.data[
    0:0 + 188
]

array([['ANONYMOUS LOGON@C457', 'ANONYMOUS LOGON@C457', 'C457', ...,
        'LogOff', 'Success', 0],
       ['ANONYMOUS LOGON@C467', 'ANONYMOUS LOGON@C467', 'C467', ...,
        'LogOff', 'Success', 0],
       ['ANONYMOUS LOGON@C586', 'ANONYMOUS LOGON@C586', 'C586', ...,
        'LogOff', 'Success', 0],
       ...,
       ['U968@DOM1', 'U968@DOM1', 'C822', ..., 'LogOn', 'Success', 0],
       ['U968@DOM1', 'U968@DOM1', 'C822', ..., 'LogOn', 'Success', 0],
       ['U9927@DOM1', 'U9927@DOM1', 'C20919', ..., 'LogOn', 'Success', 0]],
      dtype=object)

In [411]:
env.current_step = 0

In [412]:
list1 = []
starting_value = 0
step_size = env.base_data.loc[env.index_array[env.current_step]].__len__()


for i in env.index_array[:-1]:
    window_start = starting_value
    window_end = starting_value + step_size
    window_size = (window_start, window_end)
    list1.append(window_size)

    env.current_step += 1
    starting_value += step_size
    step_size = env.base_data.loc[env.index_array[env.current_step]].__len__()

In [414]:
len(list1)

62224

In [387]:
env.index_array

Int64Index([715589, 715590, 715591, 715592, 715593, 715594, 715595, 715596,
            715597, 715598,
            ...
            777804, 777805, 777806, 777807, 777808, 777809, 777810, 777811,
            777812, 777813],
           dtype='int64', name='Time Stamp', length=62225)

In [386]:
env.reader.base_data.values

array([['ANONYMOUS LOGON@C457', 'ANONYMOUS LOGON@C457', 'C457', ...,
        'LogOff', 'Success', 0],
       ['ANONYMOUS LOGON@C467', 'ANONYMOUS LOGON@C467', 'C467', ...,
        'LogOff', 'Success', 0],
       ['ANONYMOUS LOGON@C586', 'ANONYMOUS LOGON@C586', 'C586', ...,
        'LogOff', 'Success', 0],
       ...,
       ['U9861@DOM1', 'U9861@DOM1', 'C457', ..., 'LogOff', 'Success', 0],
       ['U996@DOM1', 'U996@DOM1', 'C10', ..., 'LogOff', 'Success', 0],
       ['U996@DOM1', 'U996@DOM1', 'C3173', ..., 'LogOff', 'Success', 0]],
      dtype=object)

In [13]:
env.reader.base_data

,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,target
Time Stamp,,,,,,,,,
715589,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,0
715589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,0
...,...,...,...,...,...,...,...,...,...
777813,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,0
777813,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,0
777813,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,0
777813,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,0
777813,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,0

In [16]:
env.reader.base_data.index.drop_duplicates()

Int64Index([715589, 715590, 715591, 715592, 715593, 715594, 715595, 715596,
            715597, 715598,
            ...
            777804, 777805, 777806, 777807, 777808, 777809, 777810, 777811,
            777812, 777813],
           dtype='int64', name='Time Stamp', length=62225)

In [12]:
env.step()

array(['C104$@DOM1', 'C104$@DOM1', 'C105', 'C104', '?', '?', 'TGS',
       'Success', 0], dtype=object)