# Increasing the Notebook Size

In [25]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [26]:
# Importing Native Python Libraries
import os
import math
import random
from collections import namedtuple, deque
from itertools import count

# Importing Numpy and Pandas
import numpy as np
import pandas as pd
# import modin.pandas as pd

# Importing Matplotlib
import matplotlib
import matplotlib.pyplot as plt

# Imorting Numba
from numba import jit

# Importing TA-Lib
import talib

# Importing RL Libraries
import gymnasium as gym

# Importing TQDM to track cell progress
from tqdm import tqdm

# Ignoring Warnings
import warnings
warnings.filterwarnings('ignore')

# Code to Initially Import Network Activity Log to Pandas DataFrame

## John's Method

In [2]:
# chunk_size = 100000  # Adjust the chunk size according to your available memory
# chunks = []
# count = 0
# for chunk in pd.read_csv('auth.txt', chunksize=chunk_size):
#     # Process each chunk or store it in a list for later processing
#     chunks.append(chunk)
#     count += 1
#     if count == 2000:
#         break

# # Concatenate the chunks into a single DataFrame if needed
# df = pd.concat(chunks)

# # Renaming all of our column headers
# df = df.rename({'1':'time', 'ANONYMOUS LOGON@C586':'source', 'ANONYMOUS LOGON@C586.1':'dest', 'C1250':'source_pc', 'C586':'dest_pc', 'NTLM':'auth_type', 'Network':'logon_type', 'LogOn':'auth_orient'},axis=1)
# df = df[1:]
# df = df.set_index('time')

# del chunk, chunks # Chunks were only used to build dataframe deleting to help with memory management

# Visualizing our Initial DataFrame

In [3]:
# df

In [4]:
# del df # Memory Management

# Code to Initially Import CSV Data to Pandas DataFrame

## Zach's Method

In [5]:
# %%time
# df_2 = pd.read_csv("C:/Users/zjshe/Documents/02. ECU MS CS/06. Summer 2023/CSCI 5503 - Intelligent Cloud-based Anomalous Behavior Detection/04. Datasets/Los Alamos Multi_Source Cybersecurity Events/auth.txt", 
#                    sep=",", 
#                    names=['Time Stamp', 'Source User @ Domain', 'Destination User @ Domain', 'Source Computer', 'Source Destination',  'Authentication Type', 'Logon Type', 'Auth Orientation', 'Success/Failure'])

In [6]:
# Code to Verify Table was uploaded Correctly
# df_2

# Importing Filetered Data

In [7]:
%%time
fd_df = pd.read_csv('./data_files/Fileterd_Data').copy()

CPU times: total: 9.25 s
Wall time: 9.27 s

# Importing the Redteam Text to DataFrame

In [8]:
red_df = pd.read_csv('./data_files/redteam.txt')
red_df = red_df.rename({'150885':'time', 'U620@DOM1':'user_domain', 'C17693':'source_pc', 'C1003':'dest_pc'},axis=1)
red_df = red_df.set_index('time')
red_df

        user_domain source_pc dest_pc
time
151036    U748@DOM1    C17693    C305
151648    U748@DOM1    C17693    C728
151993   U6115@DOM1    C17693   C1173
153792    U636@DOM1    C17693    C294
155219    U748@DOM1    C17693   C5693
...             ...       ...     ...
2552687   U655@DOM1    C17693    C828
2552687   U655@DOM1    C17693    C828
2552687   U655@DOM1    C17693    C828
2552687   U655@DOM1    C17693    C828
2557047   U737@DOM1    C19932    C108

[748 rows x 3 columns]

In [9]:
target_df = red_df[50:250]

# Creating a List to Find RedTeam Activity in Network Activity Log

In [10]:
target_array = []
for i in target_df.values:
    result = " ".join(i)
    target_array.append(result)

In [11]:
target_array

['U1653@DOM1 C17693 C2669',
 'U293@DOM1 C17693 C3153',
 'U8946@DOM1 C17693 C1610',
 'U293@DOM1 C17693 C3153',
 'U10379@C3521 C17693 C3521',
 'U293@DOM1 C17693 C3153',
 'U8946@DOM1 C17693 C1124',
 'U293@DOM1 C17693 C3153',
 'U8946@DOM1 C17693 C3199',
 'U293@DOM1 C17693 C3153',
 'U8946@DOM1 C17693 C11727',
 'U8601@DOM1 C17693 C754',
 'U212@DOM1 C17693 C126',
 'U212@DOM1 C17693 C126',
 'U212@DOM1 C17693 C126',
 'U8946@DOM1 C17693 C9945',
 'U8946@DOM1 C17693 C9945',
 'U8946@DOM1 C17693 C9945',
 'U4978@DOM1 C17693 C1448',
 'U8946@DOM1 C17693 C9945',
 'U3905@DOM1 C17693 C9945',
 'U995@DOM1 C17693 C1014',
 'U8601@DOM1 C17693 C20819',
 'U8601@DOM1 C17693 C20819',
 'U8601@DOM1 C17693 C18626',
 'U8601@DOM1 C17693 C18626',
 'U288@DOM1 C17693 C1222',
 'U2837@DOM1 C17693 C89',
 'U2837@DOM1 C17693 C1484',
 'U2837@DOM1 C17693 C8490',
 'U349@DOM1 C17693 C3601',
 'U2837@DOM1 C17693 C1784',
 'U2837@DOM1 C17693 C1784',
 'U2837@DOM1 C17693 C1784',
 'U2837@DOM1 C17693 C2519',
 'U8946@DOM1 C17693 C11194',
 'U2837@DOM1 C17693 C395',
 'U8946@DOM1 C17693 C10577',
 'U8601@DOM1 C17693 C18872',
 'U293@DOM1 C17693 C2597',
 'U293@DOM1 C17693 C2609',
 'U250@DOM1 C17693 C2849',
 'U293@DOM1 C17693 C3422',
 'U293@DOM1 C17693 C3153',
 'U293@DOM1 C17693 C42',
 'U1600@DOM1 C17693 C92',
 'U1600@DOM1 C17693 C16088',
 'U1600@DOM1 C17693 C92',
 'U349@DOM1 C17693 C886',
 'U349@DOM1 C17693 C886',
 'U8601@DOM1 C17693 C10817',
 'U4353@DOM1 C17693 C15232',
 'U349@DOM1 C17693 C801',
 'U4856@DOM1 C17693 C1015',
 'U5087@DOM1 C17693 C1448',
 'U5087@DOM1 C17693 C359',
 'U5087@DOM1 C17693 C21963',
 'U5087@DOM1 C17693 C359',
 'U5087@DOM1 C17693 C21963',
 'U5087@DOM1 C17693 C21963',
 'U5087@DOM1 C17693 C1268',
 'U5087@DOM1 C17693 C353',
 'U9763@DOM1 C17693 C353',
 'U9763@DOM1 C17693 C21814',
 'U5087@DOM1 C17693 C21814',
 'U795@DOM1 C17693 C10005',
 'U5087@DOM1 C17693 C353',
 'U9947@DOM1 C17693 C20966',
 'U9947@DOM1 C17693 C853',
 'U9947@DOM1 C17693 C853',
 'U9947@DOM1 C17693 C853',
 'U9947@DOM1 C17693 C923',
 'U882@DOM1 C17693 C11039',
 'U882@DOM1 C17693 C1616',
 'U8777@C583 C17693 C583',
 'U882@DOM1 C17693 C1616',
 'U9947@DOM1 C17693 C346',
 'U9947@DOM1 C17693 C20203',
 'U1450@DOM1 C17693 C12448',
 'U9947@DOM1 C17693 C20203',
 'U1450@DOM1 C17693 C12448',
 'U8777@C583 C17693 C583',
 'U8777@C1500 C17693 C1500',
 'U1450@DOM1 C17693 C12448',
 'U9947@DOM1 C17693 C346',
 'U9947@DOM1 C17693 C1479',
 'U8777@C3388 C17693 C3388',
 'U1450@DOM1 C17693 C12448',
 'U374@DOM1 C17693 C1461',
 'U1450@DOM1 C17693 C1119',
 'U2575@DOM1 C17693 C19156',
 'U2575@DOM1 C17693 C19156',
 'U1450@DOM1 C17693 C18113',
 'U374@DOM1 C17693 C1461',
 'U1450@DOM1 C17693 C18113',
 'U9947@DOM1 C17693 C19803',
 'U9947@DOM1 C17693 C17425',
 'U9947@DOM1 C17693 C19803',
 'U9947@DOM1 C17693 C19803',
 'U3718@DOM1 C17693 C9692',
 'U9947@DOM1 C17693 C7131',
 'U2575@DOM1 C17693 C8172',
 'U342@DOM1 C17693 C7503',
 'U342@DOM1 C17693 C7503',
 'U737@DOM1 C17693 C7597',
 'U737@DOM1 C17693 C2578',
 'U6572@DOM1 C17693 C90',
 'U737@DOM1 C17693 C21814',
 'U2575@DOM1 C17693 C1477',
 'U9763@DOM1 C17693 C21814',
 'U162@DOM1 C17693 C4845',
 'U162@DOM1 C17693 C3292',
 'U2575@DOM1 C17693 C7597',
 'U314@DOM1 C17693 C2914',
 'U737@DOM1 C17693 C19356',
 'U162@DOM1 C17693 C798',
 'U737@DOM1 C17693 C302',
 'U737@DOM1 C17693 C1125',
 'U737@DOM1 C17693 C3437',
 'U642@DOM1 C17693 C2648',
 'U642@DOM1 C17693 C2648',
 'U737@DOM1 C17693 C6513',
 'U737@DOM1 C17693 C15197',
 'U3635@DOM1 C17693 C17806',
 'U1653@DOM1 C17693 C395',
 'U1653@DOM1 C17693 C754',
 'U1653@DOM1 C17693 C706',
 'U1653@DOM1 C17693 C231',
 'U1653@DOM1 C17693 C2669',
 'U3635@DOM1 C17693 C16467',
 'U342@DOM1 C17693 C6487',
 'U342@DOM1 C17693 C6487',
 'U342@DOM1 C17693 C113',
 'U3635@DOM1 C17693 C2816',
 'U342@DOM1 C17693 C458',
 'U3635@DOM1 C17693 C21664',
 'U3635@DOM1 C17693 C2085',
 'U342@DOM1 C17693 C3586',
 'U3635@DOM1 C17693 C19444',
 'U3635@DOM1 C17693 C917',
 'U3635@DOM1 C17693 C917',
 'U3635@DOM1 C17693 C12682',
 'U3635@DOM1 C17693 C12682',
 'U3635@DOM1 C17693 C2091',
 'U3635@DOM1 C17693 C1506',
 'U3635@DOM1 C17693 C12512',
 'U293@DOM1 C17693 C231',
 'U293@DOM1 C17693 C706',
 'U293@DOM1 C17693 C882',
 'U1480@DOM1 C17693 C881',
 'U1480@DOM1 C17693 C2388',
 'U293@DOM1 C17693 C46',
 'U293@DOM1 C17693 C883',
 'U1480@DOM1 C17693 C1191',
 'U1480@DOM1 C17693 C5653',
 'U293@DOM1 C17693 C633',
 'U1480@DOM1 C17693 C1183',
 'U293@DOM1 C17693 C2844',
 'U1480@DOM1 C17693 C1776',
 'U1480@DOM1 C17693 C464',
 'U293@DOM1 C17693 C5453',
 'U293@DOM1 C17693 C4161',
 'U293@DOM1 C17693 C513',
 'U1480@DOM1 C17693 C1',
 'U1480@DOM1 C17693 C1776',
 'U293@DOM1 C17693 C1215',
 'U293@DOM1 C17693 C2849',
 'U1480@DOM1 C17693 C2012',
 'U293@DOM1 C17693 C3455',
 'U293@DOM1 C17693 C4159',
 'U162@DOM1 C17693 C1006',
 'U162@DOM1 C17693 C92',
 'U293@DOM1 C17693 C801',
 'U162@DOM1 C17693 C1022',
 'U314@DOM1 C17693 C2914',
 'U293@DOM1 C17693 C11039',
 'U293@DOM1 C17693 C1737',
 'U293@DOM1 C17693 C1710',
 'U293@DOM1 C17693 C231',
 'U293@DOM1 C17693 C395',
 'U162@DOM1 C17693 C3435',
 'U162@DOM1 C17693 C3435',
 'U66@DOM1 C17693 C3435',
 'U66@DOM1 C17693 C61',
 'U1164@DOM1 C17693 C2091',
 'U66@DOM1 C17693 C307',
 'U66@DOM1 C17693 C3699',
 'U2837@DOM1 C17693 C395',
 'U2837@DOM1 C17693 C2519',
 'U2837@DOM1 C17693 C1784',
 'U2837@DOM1 C17693 C1784',
 'U2837@DOM1 C17693 C8490',
 'U2837@DOM1 C17693 C1484',
 'U2837@DOM1 C17693 C89',
 'U66@DOM1 C17693 C3755',
 'U7394@DOM1 C17693 C492',
 'U7394@DOM1 C17693 C1797',
 'U7394@DOM1 C17693 C1797',
 'U4353@DOM1 C17693 C801',
 'U66@DOM1 C17693 C2944']

# Function to Create One String from a Single Row in Network Activity DF

Jit is Numba's just-in-time compiler function\
Numba translates Python functions to optimized machine code at runtime using the industry-standard LLVM compiler library. Numba-compiled numerical algorithms in Python can approach the speeds of C or FORTRAN

In [27]:
@jit
def get_loop(input_array):
    main_array = []
    for i in input_array:
        result = " ".join(i)
        main_array.append(result)
    return main_array

In [13]:
fd = fd_df.copy()

In [14]:
fd.columns

Index(['Unnamed: 0', 'Time Stamp', 'Source User @ Domain',
       'Destination User @ Domain', 'Source Computer', 'Source Destination',
       'Authentication Type', 'Logon Type', 'Auth Orientation',
       'Success/Failure'],
      dtype='object')

# Renaming our Filtered Data DataFrame Columns

In [15]:
fd = fd.rename({
    'Source User @ Domain': 'Source_Dome', 'Destination User @ Domain': 'Dest_Dome', 'Source Computer':'Source_PC', 'Source Destination':'Destination_PC', 
    'Authentication Type':'auth_type', 'Logon Type':'logon_type', 'Success/Failure':'result',
},axis=1)

# Verifying Our Update Column Names
fd

,Unnamed: 0,Time Stamp,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result
0,137649533,715589,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success
1,137649534,715589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success
2,137649535,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success
3,137649536,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success
4,137649537,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success
...,...,...,...,...,...,...,...,...,...,...
14863570,152513103,777813,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success
14863571,152513104,777813,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success
14863572,152513105,777813,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success
14863573,152513106,777813,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success
14863574,152513107,777813,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success

In [16]:
fd[['Source_Dome', 'Source_PC', 'Destination_PC']].values[0]

array(['ANONYMOUS LOGON@C457', 'C457', 'C457'], dtype=object)

In [28]:
fd['check'] = get_loop(fd[['Source_Dome', 'Source_PC', 'Destination_PC']].values)

# Checking for Matches Against RedTeam Activity in Network Log

If a string match is found in our 'check' column against the red team log, then we can mark the 'target' column with a 1 indicating malicious activity.

In [18]:
%%time
fd['target'] = fd['check'].apply(lambda x: 1 if x in target_array else 0)
fd

CPU times: total: 22.2 s
Wall time: 22.4 s

,Unnamed: 0,Time Stamp,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,check,target
0,137649533,715589,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,ANONYMOUS LOGON@C457 C457 C457,0
1,137649534,715589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,ANONYMOUS LOGON@C467 C467 C467,0
2,137649535,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,ANONYMOUS LOGON@C586 C586 C586,0
3,137649536,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C5995 C586,0
4,137649537,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C6931 C586,0
...,...,...,...,...,...,...,...,...,...,...,...,...
14863570,152513103,777813,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,U8857@DOM1 C528 C528,0
14863571,152513104,777813,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,U953@DOM1 C803 C1065,0
14863572,152513105,777813,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,U9861@DOM1 C457 C457,0
14863573,152513106,777813,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,U996@DOM1 C10 C10,0
14863574,152513107,777813,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,U996@DOM1 C3173 C3173,0

In [20]:
fd = fd.set_index('Time Stamp')
fd

,Unnamed: 0,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,check,target
Time Stamp,,,,,,,,,,,
715589,137649533,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,ANONYMOUS LOGON@C457 C457 C457,0
715589,137649534,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,ANONYMOUS LOGON@C467 C467 C467,0
715589,137649535,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,ANONYMOUS LOGON@C586 C586 C586,0
715589,137649536,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C5995 C586,0
715589,137649537,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,ANONYMOUS LOGON@C586 C6931 C586,0
...,...,...,...,...,...,...,...,...,...,...,...
777813,152513103,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,U8857@DOM1 C528 C528,0
777813,152513104,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,U953@DOM1 C803 C1065,0
777813,152513105,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,U9861@DOM1 C457 C457,0
777813,152513106,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,U996@DOM1 C10 C10,0
777813,152513107,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,U996@DOM1 C3173 C3173,0

# Saving our DataFrame to a CSV for Later use

In [21]:
fd.to_csv('./data_files/Full_Data_2.csv')

# Importing Data with Anomalous Labels

In [22]:
%%time
temp = pd.read_csv('./data_files/Full_Data_2.csv')

CPU times: total: 16.3 s
Wall time: 16.4 s

In [24]:
temp.columns
temp = temp.drop(['Unnamed: 0','check'],axis=1)
temp

,Time Stamp,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,target
0,715589,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,Success,0
1,715589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,Success,0
2,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,Success,0
3,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,Success,0
4,715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,Success,0
...,...,...,...,...,...,...,...,...,...,...
14863570,777813,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,Success,0
14863571,777813,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,Success,0
14863572,777813,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,Success,0
14863573,777813,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,Success,0
14863574,777813,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,Success,0

# End of Used Jupyter Notebook Book Code

# All Lines Below This Were For Research and Exploratory Purposes

In [29]:
temp['result'] = np.where(temp['result']=='Success', 1, 0)

In [30]:
temp = temp.set_index('Time Stamp')
temp

,Source_Dome,Dest_Dome,Source_PC,Destination_PC,auth_type,logon_type,Auth Orientation,result,target
Time Stamp,,,,,,,,,
715589,ANONYMOUS LOGON@C457,ANONYMOUS LOGON@C457,C457,C457,?,Network,LogOff,1,0
715589,ANONYMOUS LOGON@C467,ANONYMOUS LOGON@C467,C467,C467,?,Network,LogOff,1,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C586,C586,?,Network,LogOff,1,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C5995,C586,NTLM,Network,LogOn,1,0
715589,ANONYMOUS LOGON@C586,ANONYMOUS LOGON@C586,C6931,C586,NTLM,Network,LogOn,1,0
...,...,...,...,...,...,...,...,...,...
777813,U8857@DOM1,U8857@DOM1,C528,C528,?,Network,LogOff,1,0
777813,U953@DOM1,U953@DOM1,C803,C1065,Kerberos,Network,LogOn,1,0
777813,U9861@DOM1,U9861@DOM1,C457,C457,?,Network,LogOff,1,0
777813,U996@DOM1,U996@DOM1,C10,C10,?,Network,LogOff,1,0
777813,U996@DOM1,U996@DOM1,C3173,C3173,?,Network,LogOff,1,0

In [ ]:
temp['Auth Orientation'].value_counts()

In [ ]:
enc = OneHotEncoder()

In [ ]:
train = temp.drop(['target'],axis=1)

In [ ]:
temp

In [ ]:
temp['result']

In [ ]:
new.loc[715599]

In [ ]:
new.loc[715589 + 10]

In [ ]:
new['Source_PC']

In [ ]:
new[
    new['Source_PC'] == 'C17693'
]

In [ ]:
new[ 
    new['target'] == 1
]

In [ ]:
new[
    new['logon_type'] == 'Network'
]

In [ ]:
new[ 
    new['target'] == 1
]['Source_PC'].value_counts()

In [ ]:
new[ 
    new['target'] == 1
]['Destination_PC'].value_counts()

In [ ]:
new[ 
    new['target'] == 0
]['Destination_PC'].value_counts()

In [ ]:
new[ 
    new['target'] == 1
]['auth_type'].value_counts()

In [ ]:
new[ 
    new['target'] == 0
]['auth_type'].value_counts()

In [ ]:
new[ 
    new['target'] == 1
]['Dest_Dome'].value_counts()

In [ ]:
new.index

In [ ]:
new.to_csv('target_data.csv')

In [ ]:
new[
    new['target'] == 1
]

In [ ]:
new['source']

In [ ]:
new['source'].values[0].split()

In [ ]:
test = new.copy()

In [ ]:
test[['user', 'domain']] = df['source'].str.split('@', n=1, expand=True)

In [ ]:
from lightgbm import LGBMClassifier

In [ ]:
model = LGBMClassifier(
    boosting_type='rf',
    num_leaves=440,
    max_depth=21,
    n_estimators=100,
    min_child_samples=10,
    n_jobs=2,
    random_state=5
)

In [ ]:
new['target'].value_counts()

In [ ]:
final_array = []
for i in target_array:
    if i in

In [ ]:
target_array[0] in new['test'].values

In [ ]:
@jit
def get_me(input_array):
    final_array = []
    for i in input_array:

In [ ]:
main

In [ ]:
main_array = []
for i in df[['source', 'source_pc', 'dest_pc']].values:
    result = " ".join(i)
    main_array.append(result)
main_array

In [ ]:
del main_array, i, result

In [ ]:
target_tuple = tuple()
main_tuple = tuple()

In [ ]:
values = []
for i in target.values:
    target_set = set(i)
    for main in df[['source', 'source_pc', 'dest_pc']].values:
        main_set = set(main)
        if target_set == main_set:
            values.append(1)
        else:
            values.append(0)

In [ ]:
main_tuple = tuple()

In [ ]:
new = df.loc[target.index]

In [ ]:
new_target = target.copy()
new_target = target.reset_index()
new_target

In [ ]:
new_target = new_target.set_index('source_pc')
new_target

In [ ]:
new

In [ ]:
new_df = new.copy()

In [ ]:
new_df = new_df.reset_index()
new_df

In [ ]:
new_df = new_df.set_index('source_pc')
new_df

In [ ]:
new_df.loc[new_target.index]

In [ ]:
target

In [ ]:
items = []
for i in new['source_pc'].values:
    for n in target['source_pc'].values:
        if i == n:
            items.append()

In [ ]:
new

In [ ]:
del red 
del df
# del chunks
# del chunk

In [ ]:
del chunks
del chunk